### Get Feed (articles)
GET {{host}}/articles
Authorization: Bearer {{token}}

### Create an article
POST {{host}}/article
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "article": {
        "title":"new user",
        "description": "Ever wonder how?",
        "body": "hello it's react + vue ",
        "tagList": ["reactjs", "vuejs"]
    }
}

> {% client.global.set('slug', response.body.article.slug) %}}


### Get article by slug
GET {{host}}/article/{{slug}}


### Favourite an article with slug

POST {{host}}/article/{{slug}}/favourite
Authorization: Bearer {{token}}


### Unlike an article

DELETE {{host}}/article/{{slug}}/favourite
Authorization: Bearer {{token}}


### Delete article by slug
DELETE {{host}}/article/{{slug}}
Authorization: Bearer {{token}}


### Update Article by slug
PUT {{host}}/article/{{slug}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "article": {
        "title":"new article",
        "description": "with validation",
        "body": "hello it's react + wow ",
        "tagList": ["reactjs", "wowjs"]
    }
}

> {% client.global.set('slug', response.body.article.slug) %}}
