@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJraWVmZXI5IiwiZW1haWwiOiJraWVmZXJAZ21haWwuY29tIiwiaWF0IjoxNjQ4NDYxNDY1fQ.XVwTnMmq345tF0DqoUUg-gI-Ru08N03iObnomb2rLBc

@slug=new-article-2sii02

### Create an article
POST {{host}}/article
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "article": {
        "title":"How to learn reactJs",
        "description": "Ever wonder how?",
        "body": "hello it's react + vue ",
        "tagList": ["reactjs", "vuejs"]
    }
}

### Get article by slug
GET {{host}}/article/{{slug}}


### Delete article by slug
DELETE {{host}}/article/{{slug}}
Authorization: Bearer {{token}}


### Update Article by slug
PUT {{host}}/article/{{slug}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "article": {
        "title":"new article",
        "description": "with validation",
        "body": "hello it's react + wow ",
        "tagList": ["reactjs", "wowjs"]
    }
}