### Get profile from username

GET {{host}}/profiles/kiefer2
Authorization: Bearer {{token}}

### follow a profile

POST {{host}}/profiles/kiefer2/follow
Authorization: Bearer {{token}}


### Unfollow a profile
DELETE {{host}}/profiles/kiefer2/follow
Authorization: Bearer {{token}}
