### Register a user
POST {{host}}/users
Content-Type: application/json

{
  "user": {
    "username":"newuser",
    "email": "newuser@gmail.com",
    "password":"newuser"
  }
}

> {%
    client.global.set("token", response.body.user.token);
%}

### Login a user
POST {{host}}/users/login
Content-Type: application/json

{
    "user":{
        "password":"kiefer",
        "email": "kiefer@gmail.com"
    }
}

> {%
    client.global.set("token", response.body.user.token);
%}



### Get current user
GET  {{host}}/user
Authorization: Bearer {{token}}


### Update user
PUT {{host}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user":{
    "image": "hello image1213",
    "bio": "hello it's me2"
}
}
